In [3]:
import numpy as np

In [5]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
data = np.random.randint(0,100,(10,2))

In [8]:
data

array([[10, 58],
       [50, 96],
       [27, 26],
       [52, 55],
       [45, 22],
       [73, 69],
       [40, 11],
       [50,  1],
       [62, 59],
       [ 5, 51]])

In [10]:
scalar_model = MinMaxScaler()

In [11]:
type(scalar_model)

sklearn.preprocessing.data.MinMaxScaler

In [12]:
scalar_model.fit(data)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [13]:
scalar_model.transform(data)

array([[0.07352941, 0.6       ],
       [0.66176471, 1.        ],
       [0.32352941, 0.26315789],
       [0.69117647, 0.56842105],
       [0.58823529, 0.22105263],
       [1.        , 0.71578947],
       [0.51470588, 0.10526316],
       [0.66176471, 0.        ],
       [0.83823529, 0.61052632],
       [0.        , 0.52631579]])

In [14]:
scalar_model.fit_transform(data)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

array([[0.07352941, 0.6       ],
       [0.66176471, 1.        ],
       [0.32352941, 0.26315789],
       [0.69117647, 0.56842105],
       [0.58823529, 0.22105263],
       [1.        , 0.71578947],
       [0.51470588, 0.10526316],
       [0.66176471, 0.        ],
       [0.83823529, 0.61052632],
       [0.        , 0.52631579]])

In [17]:
import pandas as pd

In [19]:
my_data = np.random.randint(0,101,(50,4))

In [22]:
data = pd.DataFrame(data = my_data, columns = ['f1', 'f2', 'f3', 'label'])

In [23]:
data

     f1   f2   f3  label
0    78   56   45     59
1    78   35   98     24
2    69    0   61     30
3    58   77   91     47
4    47   95   13     56
5    44    4  100      5
6    90    8   20     43
7    70   85   59     43
8    30   19   81     79
9    23    4    6     14
10   88   78   67     59
11   56   83   39     52
12   58   21   86     43
13   79   90   47     22
14   88   66   82     47
15   64   98   36     64
16   20   50   33     28
17   84   43    8      2
18   86   19   89     44
19   11   79   73     40
20   17   43   43     36
21   95   30   39     84
22   71    0   37     53
23   93   67   72     14
24   42   85   55     29
25   11   10   24     24
26   62   58    0     43
27   65   25   98     45
28   39   93   33     87
29  100   77   27     62
30   73   51   25     81
31   21   18   27      1
32   33  100   68     82
33   31   31   65     79
34   89   79   80     25
35   24   77   85     35
36   53    4    7     67
37   83   81   59     42
38   10   74   33     13
39   64   87   41     70
40   88   29   83     42
41    0   54   60     34
42   21   31   34     45
43   59    6   71     54
44   22    6   24     43
45   50   21   16     75
46   93   85   91     32
47   46   95   59     31
48   44   58   59     32
49   88   86   90     63

In [25]:
X = data[['f1','f2','f3']]

In [26]:
X

     f1   f2   f3
0    78   56   45
1    78   35   98
2    69    0   61
3    58   77   91
4    47   95   13
5    44    4  100
6    90    8   20
7    70   85   59
8    30   19   81
9    23    4    6
10   88   78   67
11   56   83   39
12   58   21   86
13   79   90   47
14   88   66   82
15   64   98   36
16   20   50   33
17   84   43    8
18   86   19   89
19   11   79   73
20   17   43   43
21   95   30   39
22   71    0   37
23   93   67   72
24   42   85   55
25   11   10   24
26   62   58    0
27   65   25   98
28   39   93   33
29  100   77   27
30   73   51   25
31   21   18   27
32   33  100   68
33   31   31   65
34   89   79   80
35   24   77   85
36   53    4    7
37   83   81   59
38   10   74   33
39   64   87   41
40   88   29   83
41    0   54   60
42   21   31   34
43   59    6   71
44   22    6   24
45   50   21   16
46   93   85   91
47   46   95   59
48   44   58   59
49   88   86   90

In [27]:
Y = data['label']

In [28]:
Y

0     59
1     24
2     30
3     47
4     56
5      5
6     43
7     43
8     79
9     14
10    59
11    52
12    43
13    22
14    47
15    64
16    28
17     2
18    44
19    40
20    36
21    84
22    53
23    14
24    29
25    24
26    43
27    45
28    87
29    62
30    81
31     1
32    82
33    79
34    25
35    35
36    67
37    42
38    13
39    70
40    42
41    34
42    45
43    54
44    43
45    75
46    32
47    31
48    32
49    63
Name: label, dtype: int64

In [29]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=101)

In [34]:
X_train.shape

(35, 3)

In [35]:
X_test.shape

(15, 3)